/**
* counterbalance.js
*
* Counterbalances the order of conditions within a block using a Williams design
* (a balanced Latin square in which every condition follows every other equally often)
*/

const MODE_LETTER = { classic: "c", dynamic: "d", neutral: "n" };

const GROUP_CODES = ["cdn", "cnd", "dcn", "dnc", "ncd", "ndc"];

// Maps a cursor order to its GROUP_CODES index
export function groupIndex(cursorOrder) {
   const code = cursorOrder.map((m) => MODE_LETTER[m]).join("");
   const i = GROUP_CODES.indexOf(code);
   return i;
}

/*
* Builds an n x n Williams Latin square. The first row is generated by the standard
* zig-zag sequence (0, n-1, 1, n-2, ...); each subsequent row shifts it by one modulo n.
* Returns an array of rows, each row a permutation of [0, n-1].
*/
function williams(n) {
   const first = [];
   for (let k = 0; k < n; k++) {
      first.push(k % 2 === 0 ? k / 2 : n - (k + 1) / 2);
   }
   return Array.from({ length: n }, (_, i) => first.map((v) => (v + i) % n));
}

/*
* Selects one Williams row as the condition order for a single block. The row index
* combines the participant group, the cursor mode, the round and the axis so that
* every paricipant walks through the square deterministically and across the whole
* design, all rows are used equally often.
*/
export function conditionOrder(n, group, modeIndex, round, axisIndex = 0) {
   const row = (group + modeIndex + (n / 2) * round + 2 * axisIndex) % n;
   return williams(n)[row];
}
